[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "aa-memberstore-plugin"
description = "Memberstore plugin for Alliance Auth"
readme = "README.md"
keywords = [
    "allianceauth",
    "memberstore",
]
license = { file = "LICENSE" }
authors = [
    { name = "Nicolai Søndergaard", email = "Nicolai.Sondergaard@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "allianceauth>=4.3.1,<5",
]
urls.Changelog = "https://github.com/ppfeufer/aa-example-plugin/blob/master/CHANGELOG.md"
urls."Issue / Bug Reports" = "https://github.com/ppfeufer/aa-example-plugin/issues"

[tool.hatch.version]
path = "example/__init__.py"

[tool.hatch.build]
include = [
    "/example",
]
